<?php

namespace Modules\Events\Models;

use App\Models\User;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Modules\Chat\Models\Chat;

class Event extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'title',
        'category_id',
        'user_id',
        'thumbnail_url',
        'description',
        'coordinate_lat',
        'coordinate_lng',
        'country_iso',
        'planing_time',
        'is_happened',
        'slots'
    ];

    protected $casts = ['planing_time' => 'datetime', 'is_happened' => 'boolean'];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function members(): HasMany
    {
        return $this->hasMany(Member::class);
    }

    public function chat(): \Illuminate\Database\Eloquent\Relations\MorphTo
    {
        return $this->morphTo(Chat::class, 'chatable');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function (Event $event) {
            $event->chat()->create([]);
        });
    }
}
